---
- name: Install Apache from an MSI 
  hosts: all 
 
  tasks:
    - name: Download the Apache installer
      win_get_url:
        url: 'https://raw.githubusercontent.com/mehmetvatansever/my-repository/master/clear.ps1'
        dest: 'C:\Windows\Temp\clear.ps1'
        
    - name: Run remote PowerShell Script
      win_command: powershell.exe -ExecutionPolicy ByPass -File C:\Windows\Temp\clear.ps1
