---
- name: test raw module
  hosts: all
  tasks:
     - name: Download the Apache installer
      win_get_url:
        url: 'https://github.com/mehmetvatansever/my-repository/blob/master/clear.ps1'
        dest: 'C:\Windows\Temp\clear.ps1'
    
    
    - name: Run remote PowerShell Script
      win_shell: C:\Windows\Temp\clear.ps1
