---
- name: Install Apache from an MSI 
  hosts: all 
 
  tasks:
    - name: Download the Apache installer
      win_get_url:
        url: 'https://github.com/mehmetvatansever/my-repository/blob/master/clear.ps1'
        dest: 'C:\Windows\Temp\clear.ps1'

    - name: Install MSI
      win_shell: 
        path: 'C:\Windows\Temp\clean.ps1'
        state: present
