---
- name: Install Apache from an MSI 
  hosts: all 
 
  tasks:
    - name: Download the Apache installer
      win_get_url:
        url: 'http://archive.apache.org/dist/httpd/binaries/win32/httpd-2.0.65-win32-x86-no_ssl.msi'
        dest: 'C:\Users\Administrator\Downloads\httpd-2.0.65-win32-x86-no_ssl.msi'

    - name: Install MSI
      win_package: 
        path: 'C:\Users\Administrator\Downloads\httpd-2.0.65-win32-x86-no_ssl.msi'
        state: present
