---
- name: Install Sophos Endpoint & Encryption
  hosts: all 
 
  tasks:
    - name: Download Sophos EXE Packet
      win_get_url:
        url: 'https://github.com/mehmetvatansever/my-repository/blob/master/sophos/SophosSetup.exe?raw=true'
        dest: 'C:\Windows\Temp\SophosSetup.exe'
        
    - name: start_platform
      win_command: C:\Windows\Temp\SophosSetup.exe --quiet
